Feature: Generate traces following given hold/guide notes
sevenc-nanashi/MikuMikuWorld4CC pull request #50
Opened 2024-08-25 02:26 UTC by GuanYixuan

This pull request adds a right-click menu item to generate traces according to given hold/guide notes' shape and current division. This will satisfy issue #41 upon successful merge.

The menu item includes two sub-options "*add traces for*" and "*convert to traces*", which is able to create guided or non-guided trace patterns, respectively. Here's a demonstration:

- The origin and the right-click menu:
![origin](https://github.com/user-attachments/assets/a888009d-20ff-4431-aab2-5de5abbfdcd6)

- After choosing "*add traces for hold*":
Notice traces that will overlap with existing hold start/end judgements are not generated.
![add](https://github.com/user-attachments/assets/6a9c29a4-4dce-4166-85ae-e46414f2eaa1)

- After choosing "*convert hold to traces*":
![convert](https://github.com/user-attachments/assets/bccdfbdb-2e77-4dbb-92c2-d380b9cfd982)

This pr only implements the feature body, while translations are not added yet.
Please feel free to make/suggest further modifications regarding the feature's name, translations, code style and so on.

2024-08-25 03:32 UTC, sevenc-nanashi requested changes
https://github.com/user-attachments/assets/f4b1cc24-55f5-469c-89e2-11ae6083ba50

Thank you for contribution!
But it looks like this feature creates a note which causes mmw to crash, could you fix that?

2024-08-25 03:32 UTC, sevenc-nanashi commented on MikuMikuWorld/ScoreEditorTimeline.cpp
> +			if (ImGui::BeginMenu(getString("hold_to_traces"), context.selectionHasHold())) {
Could you add `hold_to_traces` and some texts below to `.template.csv`?

2024-08-25 03:32 UTC, sevenc-nanashi commented on MikuMikuWorld/ScoreContext.cpp
> +			const Note& hold_start = score.notes[target_slide_id];
could you use `camelCase` for variables? (Sorry I haven't setup linters)

2024-08-25 03:58 UTC, GuanYixuan commented
OK, I will take a look at these this afternoon. (It's weird that I left such an obvious bug undiscovered😂

2024-08-25 12:05 UTC, GuanYixuan commented
It seems like the bug is caused by `score.note[]` creates empty notes when a non-exist id is passed in.
The problem should be now fixed and both code style and `.template.csv` are updated according to the request.

2024-08-31 11:54 UTC, sevenc-nanashi approved these changes
Sorry for late reviews; Looks good to me! Thank you for contributing.

2024-08-31 11:56 UTC, merged